### 1. Fit and Transform Separately

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
from pandas import DataFrame

text_data  = [ "GFG is providing a new Deep Learning Course which is really good",
               "We will be studying Deep Learning from today",
               "I want a Deep sleep today"]

vec = CountVectorizer()
vec = vec.fit(text_data)

data_transformed = vec.transform(text_data)

df = DataFrame(data_transformed.toarray(), columns = vec.vocabulary_)
df

   gfg  is  providing  new  deep  ...  studying  from  today  want  sleep
0    0   1          1    0     1  ...         0     0      0     1      0
1    1   0          1    1     0  ...         1     0      1     0      1
2    0   0          1    0     0  ...         1     1      0     0      0

[3 rows x 18 columns]

### 2. Fit and Transform Combined

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
from pandas import DataFrame

text_data  = [ "GFG is providing a new Deep Learning Course which is really good",
               "We will be studying Deep Learning from today",
               "I want a Deep sleep today",
               'We will be studying Deep Learning']

vec = CountVectorizer()

data_transformed = vec.fit_transform(text_data)

df = DataFrame(data_transformed.toarray(), columns = vec.vocabulary_)
df

   gfg  is  providing  new  deep  ...  studying  from  today  want  sleep
0    0   1          1    0     1  ...         0     0      0     1      0
1    1   0          1    1     0  ...         1     0      1     0      1
2    0   0          1    0     0  ...         1     1      0     0      0
3    1   0          1    0     0  ...         0     0      1     0      1

[4 rows x 18 columns]

### 3. Dealing with Stop Words

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
from pandas import DataFrame

text_data  = [ "GFG is providing a new Deep Learning Course which is really good",
               "We will be studying Deep Learning from today",
               "I want a Deep sleep today"]

vec = CountVectorizer(stop_words = 'english', lowercase = True)
vec = vec.fit(text_data)

data_transformed = vec.transform(text_data)

df = DataFrame(data_transformed.toarray(), columns = vec.vocabulary_)
df

   gfg  providing  new  deep  learning  ...  good  studying  today  want  sleep
0    1          1    1     1         1  ...     1         0      0     0      0
1    0          1    0     0         1  ...     0         0      1     1      0
2    0          1    0     0         0  ...     0         1      0     1      1

[3 rows x 12 columns]

### 4. Dealing with N-Gram

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
from pandas import DataFrame

text_data  = [ "GFG is providing a new Deep Learning Course which is really good",
               "We will be studying Deep Learning from today",
               "I want a Deep sleep today"]

vec = CountVectorizer(ngram_range = (3,3))
vec = vec.fit(text_data)

data_transformed = vec.transform(text_data)

df = DataFrame(data_transformed.toarray(), columns = vec.vocabulary_)
df

   gfg is providing  is providing new  ...  want deep sleep  deep sleep today
0                 0                 1  ...                1                 0
1                 1                 0  ...                0                 1
2                 0                 0  ...                0                 0

[3 rows x 17 columns]

### 5. Count Vectorizer with Data Preprocessing

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
from pandas import DataFrame

text_data  = [ "GFG is providing a new Deep Learning Course which is really good",
               "We will be studying Deep Learning from today",
               "I want a Deep sleep today"]

vec = CountVectorizer(ngram_range = (1,1), stop_words = 'english', lowercase = True)
vec = vec.fit(text_data)

data_transformed = vec.transform(text_data)

df = DataFrame(data_transformed.toarray(), columns = vec.vocabulary_)
df

   gfg  providing  new  deep  learning  ...  good  studying  today  want  sleep
0    1          1    1     1         1  ...     1         0      0     0      0
1    0          1    0     0         1  ...     0         0      1     1      0
2    0          1    0     0         0  ...     0         1      0     1      1

[3 rows x 12 columns]